services:

  app:
    build: ./app/
    container_name: php-app
    ports:
      - "80:80"

  app-db:
    build: ./database/
    image: mysqlimage
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hiveGame
    ports:
      - '3307:3307'
    expose:
      - '3307'

  ai-docker:
    build:
      context: .
      dockerfile: AI.Dockerfile
    ports:
      - "5000:5000"
