services:

  app:
    build: ./app/
    container_name: php-app
    ports:
      - "80:80"

  app-db:
    build: ./database/
    image: mysqlimage
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hiveGame
    ports:
      - '3306:3306'
    expose:
      - '3306'

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
